# Auto-generated by Nomad for a Next.js (pnpm) project.
FROM node:22-slim

WORKDIR /app

# pnpm 9 runs native build scripts (sharp) without the pnpm 10 approval gate.
RUN npm install -g pnpm@9

# Install deps first for better layer caching.
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --no-frozen-lockfile

# Build the app.
COPY . .
# A single-app deploy has no workspace; a stray pnpm-workspace.yaml breaks pnpm.
RUN rm -f pnpm-workspace.yaml
RUN pnpm build

ENV NODE_ENV=production
# Render injects PORT (default 10000); bind to it on 0.0.0.0.
ENV PORT=10000
EXPOSE 10000

CMD ["sh", "-c", "pnpm exec next start -H 0.0.0.0 -p ${PORT:-10000}"]
